---
abstract: 'Fast, compact, powerful binary (de-)serialization'
author:
  - 'Steffen Mueller <smueller@cpan.org>, Yves Orton <yves@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Scalar::Util: '0'
  Sereal::Decoder: '4.018'
  Sereal::Encoder: '4.018'
  Test::LongString: '0'
  Test::More: '0.88'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.46, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Sereal
no_index:
  directory:
    - t
    - inc
requires:
  Sereal::Decoder: '4.018'
  Sereal::Encoder: '4.018'
  perl: '5.008'
resources:
  bugtracker: https://github.com/Sereal/Sereal/issues
  repository: git://github.com/Sereal/Sereal.git
version: '4.018'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
